import type { Metadata } from "next";
import { Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/components/site-header";
import HeaderGate from "@/components/header-gate";
import SiteFooter from "@/components/site-footer";
import FooterGate from "@/components/footer-gate";
import { Toaster } from "@/components/ui/sonner";
// import WelcomeOnboarding from "@/components/welcome-onboarding";
import SessionProviderWrapper from "@/components/session-provider";

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${roboto.variable} ${geistMono.variable} antialiased flex flex-col min-h-dvh bg-background text-foreground overflow-x-hidden`}>
        <SessionProviderWrapper>
          <HeaderGate>
            <SiteHeader />
          </HeaderGate>
          <main className="flex-1 min-h-0 flex flex-col">
            <div className="flex-1 min-h-0 w-full px-2 md:px-3">
              {children}
            </div>
          </main>
          <FooterGate>
            <SiteFooter />
          </FooterGate>
          <Toaster />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
